### ISSUE TITLE
Run SSA bot via github actions

### ISSUE THREAD

**Issue by jbesraa** [keyko-io/filecoin-large-clients-onboarding#1620]
- create a new github action that runs on each new comment in any open issue
- read the comment body
- read issue number
- pass comment body to SSA script `./ssa-check.js comment_body issue_number`

**Comment by kokal33** [comment]
Testing comment to read the body

**Comment by kokal33** [comment]
Test 1

**Comment by kokal33** [comment]
test 2

**Comment by kokal33** [comment]
test 1
